sudo: false

language: php

matrix:
  fast_finish: true

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=1

before_script:
  - composer self-update
  - composer install
  - wget https://raw.githubusercontent.com/wp-cli/sample-plugin/master/bin/install-wp-tests.sh
  - bash install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

after_script:
  - php vendor/bin/coveralls
